name: s3i_flutter
description: A library that makes it easy to communicate with the S³I (Smart Systems Service Infrastructure of the KWH4.0).
version: 0.3.0
homepage: https://github.com/LukasPoque/s3i_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
